### ISSUE TITLE
How to get log file

### ISSUE THREAD

**Issue by utya** [dji-sdk/FlightRecordParsingLib#16]
Hi. I would like to know how to retrieve a log using my custom application written using the DJI SDK. Currently, using the GetLogPath function, I can only obtain a .dat file. Is there any way I can somehow obtain a file with the .txt extension?

**Comment by dji-dev** [comment]
Agent comment from shiyao.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/89507'>Zendesk ticket #89507</a>:<br><br>Dear Developer,

Hello, thank you for contacting DJI.

We may still have some information to confirm with you. Which DJI SDK are you using specifically? Is it PSDK?

Thank you for your support of DJI products.

Best Regards,
DJI Dajiang innovation SDK technical support
<br><p><em><small>°°°</small></em></p>

**Comment by utya** [comment]
Mobile sdk com.dji:dji-sdk:4.16.4

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/89507'>Zendesk ticket #89507</a>:<br><br>Are you referring to the information in the FlighRecord folder? It is stored in the Android/data/package_Name/files/DJI/FlightRecord path.
<br><p><em><small>°°°</small></em></p>

**Comment by utya** [comment]
No files in this dir

**Comment by utya** [comment]
If we use our application with the simulator, is it possible that only a dat file is created?
