### ISSUE TITLE
Docker Error Build Step 7

### ISSUE THREAD

**Issue by vandzkianox** [dji-sdk/FlightRecordParsingLib#17]
i have a trouble when docker build step 7 RUN sh generate.sh

> [7/7] RUN sh generate.sh:
> 0.306 Which do you want to build? Please Input the number:
> 0.544 -- The C compiler identification is GNU 5.4.0
> 0.651 -- The CXX compiler identification is GNU 5.4.0
> 0.658 -- Check for working C compiler: /usr/bin/cc
> 0.708 -- Check for working C compiler: /usr/bin/cc -- works
> 0.709 -- Detecting C compiler ABI info
> 0.751 -- Detecting C compiler ABI info - done
> 0.755 -- Detecting C compile features
> 0.879 -- Detecting C compile features - done
> 0.883 -- Check for working CXX compiler: /usr/bin/c++
> 0.932 -- Check for working CXX compiler: /usr/bin/c++ -- works
> 0.933 -- Detecting CXX compiler ABI info
> 1.003 -- Detecting CXX compiler ABI info - done
> 1.006 -- Detecting CXX compile features
> 1.160 -- Detecting CXX compile features - done
> 1.164 CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
> 1.164   Could NOT find CURL (missing: CURL_INCLUDE_DIR)
> 1.164 Call Stack (most recent call first):
> 1.164   /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
> 1.164   /usr/share/cmake-3.5/Modules/FindCURL.cmake:61 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
> 1.164   CMakeLists.txt:14 (find_package)
> 1.164
> 1.164
> 1.165 -- Configuring incomplete, errors occurred!
> 1.165 See also "/parse_flyrecord/dji-flightrecord-kit/build/Ubuntu/FRSample/CMakeFiles/CMakeOutput.log".
> 1.168 make: *** No targets specified and no makefile found.  Stop.
> ------
> Dockerfile:14
> --------------------
>   12 |
>   13 |     WORKDIR /parse_flyrecord/dji-flightrecord-kit/build/Ubuntu/FRSample
>   14 | >>> RUN sh generate.sh
>   15 |
>   16 |     ENTRYPOINT ["./FRSample"]
> --------------------
> ERROR: failed to solve: process "/bin/sh -c sh generate.sh" did not complete successfully: exit code: 2

**Comment by dji-dev** [comment]
Agent comment from xiaorong.zheng in <a href='https://djisdksupport.zendesk.com/agent/tickets/89660'>Zendesk ticket #89660</a>:<br><br>Hi vandzkianox,

I hope you're having a great day! 😊

This problem is because the curl command cannot be found. You need to install the curl command and try again

Have a fantastic day!

Best regards,
DJI Developer Support Team
<br><p><em><small>°°°</small></em></p>
