### ISSUE TITLE
Compile for android

### ISSUE THREAD

**Issue by utya** [dji-sdk/FlightRecordParsingLib#20]
Hi. Can I compile DJI parser for android arm64-v8a?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/91803'>Zendesk ticket #91803</a>:<br><br>We have not attempted to use it on Android. I would like to verify this with our engineers.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-lyt** [comment]
Hi @utya .  I t is possible to convert FlightRecordParsingLib and its dependent libraries into a shared object (so) library. By doing so, you will be able to use the library in an Android project and achieve your goal of using FlightRecordParsingLib in an Android environment. You need to compile for the ndk you are using at compile time.

**Comment by utya** [comment]
To build the project, need these source files and Android NDK, or are there any specific libraries required?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/91803'>Zendesk ticket #91803</a>:<br><br>You need to cross-compile FlightRecordParsingLib for the NDK you are using, including the libraries that FlightRecordParsingLib depends on. You can find this information in FlightRecordParsingLib, and its parsing library is open source.
<br><p><em><small>°°°</small></em></p>
