### ISSUE TITLE
CORS issue while requesting DJI Keychains API

### ISSUE THREAD

**Issue by lvauvillier** [dji-sdk/FlightRecordParsingLib#31]
I am working on a WebAssembly target for this library to fully run in the browser.

This is currently not feasible because the DJI endpoint for keychain retrieval (https://dev.dji.com/openapi/v1/flight-records/keychains) cannot be called from the browser due to missing CORS headers.

I am aware that this is not directly related to this repo, but I don't know how to reach the DJI backend team to ask if it is possible to add an `Access-Control-Allow-Origin: *` header.

Thanks a lot for your help.

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/112318'>Zendesk ticket #112318</a>:<br><br>The library we provide has already implemented the key verification function. You cannot access our website to perform the verification on your own.
<br><p><em><small>°°°</small></em></p>
