### ISSUE TITLE
Terminate with error 134

### ISSUE THREAD

**Issue by DrakenXI** [dji-sdk/FlightRecordParsingLib#8]
Terminate called after throwing an instance of 'std::logic_error'
what(): basic_string::_M_construct null not valid
Aborted (core dumped)

dji-flightrecord-kit/build/Ubuntu/FRSample/FRSample DJI.txt > output.json

Ubuntu 18.04.6 LTS

**Comment by Jackfeng212** [comment]
You can try running this command on the terminal. 

export SDK_KEY=your Open API Key

Afterwards, you can conduct the test again.

**Comment by DrakenXI** [comment]
It was not the right user with the environment variable set which launch the program.
Problems solve. Thank you.

Please add an explicit error of this case to not have a core dump.
